"""add_order_date_field

Revision ID: 0d0fcf2a1281
Revises: daaddf629e95
Create Date: 2025-10-19 15:30:34.682611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0fcf2a1281'
down_revision = 'daaddf629e95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###