"""init

Revision ID: daaddf629e95
Revises: dea93c3b67f9
Create Date: 2025-10-18 21:18:35.576578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaddf629e95'
down_revision = 'dea93c3b67f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###