"""init

Revision ID: dea93c3b67f9
Revises: 0001
Create Date: 2025-10-18 18:19:42.198387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dea93c3b67f9'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_settings', 'notification_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applications', 'phone',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('applications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('applications', 'phone',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('applications', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('applications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('app_settings', 'notification_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###